from typing import Protocol
from uuid import UUID

from huginn.pipeline_control.application.read_models.executor_identity import (
    ExecutorIdentity,
)
from huginn.pipeline_control.domain.value_objects.execution_owner import ExecutionOwner


class ExecutionGuard(Protocol):
    def acquire(self, owner: ExecutionOwner) -> bool: ...
    def attach_executor(self, owner_id: UUID, identity: ExecutorIdentity) -> None: ...
    def heartbeat(self, owner_id: UUID) -> None: ...
    def release(self, owner_id: UUID) -> bool: ...
    def close(self) -> None: ...

    def settle(
        self, owner: ExecutionOwner, state: str, safe_error_code: str | None = None
    ) -> bool: ...
    def inspect(
        self, execution_id: UUID
    ) -> tuple[ExecutionOwner, ExecutorIdentity | None] | None: ...
    def reconcile(self, owner: ExecutionOwner) -> bool: ...

    def inspect_invocation(
        self, invocation_id: UUID
    ) -> tuple[ExecutionOwner, ExecutorIdentity | None] | None: ...
