from typing import Protocol
from uuid import UUID

from huginn.pipeline_control.domain.value_objects.execution_owner import ExecutionOwner


class ExecutionGuardRepository(Protocol):
    def acquire(self, owner: ExecutionOwner) -> bool: ...
    def attach_executor(
        self, owner_id: UUID, executor_pid: int, executor_started_at: str
    ) -> bool: ...
    def heartbeat(self, owner_id: UUID) -> bool: ...
    def get_active(
        self,
    ) -> tuple[ExecutionOwner | None, int | None, str | None, bool] | None: ...
    def inspect(
        self, execution_id: UUID
    ) -> tuple[ExecutionOwner | None, int | None, str | None, bool] | None: ...
    def inspect_invocation(
        self, invocation_id: UUID
    ) -> tuple[ExecutionOwner | None, int | None, str | None, bool] | None: ...
    def release(self, owner_id: UUID) -> bool: ...
