"""Account persistence contract."""

from typing import Protocol
from uuid import UUID

from huginn.management.domain.entities.account import Account, AccountStatus
from huginn.management.domain.value_objects.account import NewAccount
from huginn.management.domain.value_objects.account_role import AccountRole


class AccountRepository(Protocol):
    def get_by_id(self, account_id: UUID) -> Account | None: ...
    def get_by_id_for_update(self, account_id: UUID) -> Account | None: ...
    def get_by_normalized_username(self, username: str) -> Account | None: ...
    def get_by_normalized_username_for_update(
        self, username: str
    ) -> Account | None: ...
    def create(self, account: NewAccount) -> Account: ...
    def set_status(self, account_id: UUID, status: AccountStatus) -> Account | None: ...
    def set_password_hash(
        self, account_id: UUID, password_hash: str
    ) -> Account | None: ...
    def set_role(self, account_id: UUID, role: AccountRole) -> Account | None: ...
